/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 23:27:57 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DTO;
 
/*
 * For Table calificaciones
 */
public class Calificaciones implements java.io.Serializable, Cloneable {
    

    /* idCalificaciones, PK */
    private int idcalificaciones;

    /* puntaje */
    private double puntaje;

    /* matriculaA */
    private long matriculaa;

    /* matriculaP */
    private long matriculap;

    /* idExamen */
    private int idexamen;


    /* idCalificaciones, PK */
    public int getIdcalificaciones() {
        return idcalificaciones;
    }

    /* idCalificaciones, PK */
    public void setIdcalificaciones(int idcalificaciones) {
        this.idcalificaciones = idcalificaciones;
    }

    /* puntaje */
    public double getPuntaje() {
        return puntaje;
    }

    /* puntaje */
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }

    /* matriculaA */
    public long getMatriculaa() {
        return matriculaa;
    }

    /* matriculaA */
    public void setMatriculaa(long matriculaa) {
        this.matriculaa = matriculaa;
    }

    /* matriculaP */
    public long getMatriculap() {
        return matriculap;
    }

    /* matriculaP */
    public void setMatriculap(long matriculap) {
        this.matriculap = matriculap;
    }

    /* idExamen */
    public int getIdexamen() {
        return idexamen;
    }

    /* idExamen */
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Calificaciones))
            return false;

        Calificaciones bean = (Calificaciones) obj;

        if (this.idcalificaciones != bean.idcalificaciones)
            return false;

        if (this.puntaje != bean.puntaje)
            return false;

        if (this.matriculaa != bean.matriculaa)
            return false;

        if (this.matriculap != bean.matriculap)
            return false;

        if (this.idexamen != bean.idexamen)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Calificaciones bean = new Calificaciones();
        bean.idcalificaciones = this.idcalificaciones;
        bean.puntaje = this.puntaje;
        bean.matriculaa = this.matriculaa;
        bean.matriculap = this.matriculap;
        bean.idexamen = this.idexamen;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcalificaciones").append(" = ").append(idcalificaciones).append("]").append(sep);
        sb.append("[").append("puntaje").append(" = ").append(puntaje).append("]").append(sep);
        sb.append("[").append("matriculaa").append(" = ").append(matriculaa).append("]").append(sep);
        sb.append("[").append("matriculap").append(" = ").append(matriculap).append("]").append(sep);
        sb.append("[").append("idexamen").append(" = ").append(idexamen).append("]").append(sep);
        return sb.toString();
    }
}