/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 23:28:51 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DTO;

/*
 * For Table carrera
 */
public class Carrera implements java.io.Serializable, Cloneable {

    /* idCarrera, PK */
    private int idcarrera;

    /* nombre */
    private String nombre;

    /* duracion */
    private int duracion;

    /* idCarrera, PK */
    public int getIdcarrera() {
        return idcarrera;
    }

    /* idCarrera, PK */
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* duracion */
    public int getDuracion() {
        return duracion;
    }

    /* duracion */
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Carrera))
            return false;

        Carrera bean = (Carrera) obj;

        if (this.idcarrera != bean.idcarrera)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.duracion != bean.duracion)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Carrera bean = new Carrera();
        bean.idcarrera = this.idcarrera;
        bean.nombre = this.nombre;
        bean.duracion = this.duracion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcarrera").append(" = ").append(idcarrera).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("duracion").append(" = ").append(duracion).append("]").append(sep);
        return sb.toString();
    }
}