/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 23:28:59 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DTO;

/*
 * For Table examen
 */
public class Examen implements java.io.Serializable, Cloneable {
    

    /* idExamen, PK */
    private int idexamen;

    /* fecha */
    private java.util.Date fecha;

    /* periodo */
    private int periodo;

    /* idMateria */
    private int idmateria;

    /* idExamen, PK */
    public int getIdexamen() {
        return idexamen;
    }

    /* idExamen, PK */
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
    }

    /* fecha */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /* periodo */
    public int getPeriodo() {
        return periodo;
    }

    /* periodo */
    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }

    /* idMateria */
    public int getIdmateria() {
        return idmateria;
    }

    /* idMateria */
    public void setIdmateria(int idmateria) {
        this.idmateria = idmateria;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Examen))
            return false;

        Examen bean = (Examen) obj;

        if (this.idexamen != bean.idexamen)
            return false;

        if (this.fecha == null) {
            if (bean.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(bean.fecha)) 
            return false;

        if (this.periodo != bean.periodo)
            return false;

        if (this.idmateria != bean.idmateria)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Examen bean = new Examen();
        bean.idexamen = this.idexamen;
        if (this.fecha != null)
            bean.fecha = (java.util.Date) this.fecha.clone();
        bean.periodo = this.periodo;
        bean.idmateria = this.idmateria;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idexamen").append(" = ").append(idexamen).append("]").append(sep);
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]").append(sep);
        sb.append("[").append("periodo").append(" = ").append(periodo).append("]").append(sep);
        sb.append("[").append("idmateria").append(" = ").append(idmateria).append("]").append(sep);
        return sb.toString();
    }
}