/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 23:29:13 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAO;
import DTO.Pregunta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

/**
 * This class provides methods to populate DB Table of pregunta
 */
public class PreguntaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO pregunta ("
        + "idPregunta, pregunta, idExamen"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idPregunta, pregunta, idExamen "
        + "FROM pregunta WHERE "
        + "idPregunta = ?";

    private static final String SQL_SELECTALL =
        "SELECT "
        + "idPregunta, pregunta, idExamen "
        + "FROM pregunta";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE pregunta SET "
        + "pregunta = ?, idExamen = ? "
        + "WHERE "
        + "idPregunta = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM pregunta WHERE "
        + "idPregunta = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Pregunta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdpregunta());
            ps.setString(2, bean.getPregunta());
            ps.setInt(3, bean.getIdexamen());
            ps.executeUpdate();
        }finally {
            close(ps);
            if(conn!=null){
                conn.close();
            }
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Pregunta load(Pregunta key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdpregunta());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Pregunta) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
            if(conn!=null){
                conn.close();
            }
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Pregunta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getPregunta());
            ps.setInt(2, bean.getIdexamen());
            ps.setInt(3, bean.getIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
            if(conn!=null){
                conn.close();
            }
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Pregunta key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
            if(conn!=null){
                conn.close();
            }
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Pregunta> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Pregunta>();
        while (rs.next()) {
            Pregunta bean = new Pregunta();
            bean.setIdpregunta(rs.getInt("idPregunta"));
            bean.setPregunta(rs.getString("pregunta"));
            if (rs.wasNull())
                bean.setPregunta(null);     
            bean.setIdexamen(rs.getInt("idExamen"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }

    public List loadALL(Connection conn) throws SQLException {
      PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECTALL);            
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return  results;
            else
                return null;
        }finally {
            close(rs);
            close(ps);
            if(conn!=null){
                conn.close();
            }
        }
    }
}